name: Acceptance Tests
on:
  pull_request:
    paths-ignore:
      - "README.md"
  push:
    paths-ignore:
      - "README.md"
  schedule:
    - cron: "0 13 * * *"
jobs:
  test:
    name: Matrix Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        unifi_version:
          - "v6.5"
          - "v6"
          - "v7.0"
          - "v7.1"
          - "v7.2"
          - "v7"
          - "latest"
        terraform_version:
          - "1.2.9"
          - "1.3.0"
          - "1.3.1"
          - "1.3.2"
          - "1.3.3"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - run: make testacc-up UNIFI_VERSION=${{ matrix.unifi_version }}

      - name: TF acceptance tests
        timeout-minutes: 10
        run: make testacc TF_ACC_TERRAFORM_VERSION=${{ matrix.terraform_version }}

      - run: make testacc-down
